### PR TITLE
Make the app readable under a dark mode

### PR DESCRIPTION
**Pull request by Cangonin**
I couldn't implement everything. For now, I changed the colour of the text, but I'm blocking for the rest. We still have imo 3 problems when the dark mode is activated:
- The colour of the URL links is too dark, so we should change it
- On hover, we should change the colour of the text in the table, right now it's not readable
- When opening the modal, its background should also be black
If you see any more changes that would look good, just go ahead!

Just so that I understand, how do we inherit dark mode properties? I thought they were set in `base.css` under the `prefers-color-scheme: dark` element. Is that correct? But then, how do I define dark mode properties  for simple elements such as the hyperlink colour? I saw on the documentation (https://tailwindcss.com/docs/dark-mode) that I could manually toggle the `dark` selector (add `dark:bg-black` for example), but it doesn't seem to have any effect. Also, I don't really understand the syntax in `base.css` (eg `--color-background: var(--vt-c-black);`, where can I find documentation on that?

### CODE REVIEW

**Comment by patrik-ha** [comment]
You are right, you should be able to style any elements using `dark:some-class-here` as a class. It apparently has to be activated in the tailwind.css-config. I've committed a change that does that.

For the the dark mode properties, under the `prefers-color-scheme: dark`-element, you basically just define CSS-rules as normal. The thing that might be throwing you off is that this uses CSS-variables. You can read about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties). The main idea is that you can define colors once, and then reuse them later, so that you don't have to repeat it later.

**Comment by patrik-ha** [comment]
I've updated everything so that it's all readable, but it's not graphically very nice. It's probably nicest to implement a standard palette or something, I can look at that a bit later. It should however be pretty straight-forward now to apply CSS-rules with the `dark:`-prefix.

**Comment by patrik-ha** [comment]
It would probably also be nice to have a logo that is adapted for dark-mode (the BioAI-one).

**Comment by Cangonin** [comment]
> Instead of defining (or using Tailwind ones) CSS-rules for every single hyperlink, it might be nicer to define these once in base.css, with corresponding colors and everything. 

I agree with that. Should we do that in a next PR or do you want to fix it in this PR?

> It would probably also be nice to have a logo that is adapted for dark-mode (the BioAI-one).

Not sure we have one, I will ask around. Let's keep this one for now

**Comment by patrik-ha** [comment]
I think that setting reasonable defaults for everything should be done in a separate PR. Depending on how deep you want to go with integrating Tailwind we could just set up something like this: https://tailwindcss.com/docs/theme. I still don't think it's that crucial to do that for a web app of this size, but it's still nice to do it I guess.

**Pull request merged**
